### ISSUE TITLE
Proposal for a better looking TODO

### ISSUE THREAD

**Issue by rkrp** [techvoltage/addr-info#1]
TODO can be listed as unchecked boxes. And then checked boxes for the ones which are done.
 
- [x] Pattern scan without memory maps
- [ ]    Include entire memory for pattern scanning
 - [ ]   Remove memmem function
  - [ ]  Extend to remote processes
  - [ ]  Repair Makefile. Add entry for samples
